In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [41]:
df1=pd.read_csv("Airlines.csv")

In [42]:
df1

,id,Airline,Flight,AirportFrom,AirportTo,DayOfWeek,Time,Length,Delay
0,1,CO,269,SFO,IAH,3,15,205,1
1,2,US,1558,PHX,CLT,3,15,222,1
2,3,AA,2400,LAX,DFW,3,20,165,1
3,4,AA,2466,SFO,DFW,3,20,195,1
4,5,AS,108,ANC,SEA,3,30,202,0
...,...,...,...,...,...,...,...,...,...
539378,539379,CO,178,OGG,SNA,5,1439,326,0
539379,539380,FL,398,SEA,ATL,5,1439,305,0
539380,539381,FL,609,SFO,MKE,5,1439,255,0
539381,539382,UA,78,HNL,SFO,5,1439,313,1
539382,539383,US,1442,LAX,PHL,5,1439,301,1

In [43]:
df1.dtypes

id              int64
Airline        object
Flight          int64
AirportFrom    object
AirportTo      object
DayOfWeek       int64
Time            int64
Length          int64
Delay           int64
dtype: object

In [44]:
df1['AirportTo'].nunique()

293

In [45]:
df1.isna().sum()

id             0
Airline        0
Flight         0
AirportFrom    0
AirportTo      0
DayOfWeek      0
Time           0
Length         0
Delay          0
dtype: int64

In [46]:
df1.dropna(inplace=True)

In [47]:
df1.duplicated().sum()

np.int64(0)

In [48]:
df1.describe()

,id,Flight,DayOfWeek,Time,Length,Delay
count,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000
mean,269692.000000,2427.928630,3.929668,802.728963,132.202007,0.445442
std,155706.604461,2067.429837,1.914664,278.045911,70.117016,0.497015
min,1.000000,1.000000,1.000000,10.000000,0.000000,0.000000
25%,134846.500000,712.000000,2.000000,565.000000,81.000000,0.000000
50%,269692.000000,1809.000000,4.000000,795.000000,115.000000,0.000000
75%,404537.500000,3745.000000,5.000000,1035.000000,162.000000,1.000000
max,539383.000000,7814.000000,7.000000,1439.000000,655.000000,1.000000

In [49]:
# Function to detect outliers using IQR
def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    return outliers

In [50]:
for i in df1:
    if df1[i].dtypes in [int,float]:
        outliers = detect_outliers_iqr(df1, i)
        print(f"Feature: {i} → Outliers detected: {len(outliers)}")

Feature: id → Outliers detected: 0
Feature: Flight → Outliers detected: 0
Feature: DayOfWeek → Outliers detected: 0
Feature: Time → Outliers detected: 0
Feature: Length → Outliers detected: 25650
Feature: Delay → Outliers detected: 0

In [51]:
def remove_outliers(df, col):
    Q1 = df[col].quantile(0.25)  # 25th percentile
    Q3 = df[col].quantile(0.75)  # 75th percentile
    IQR = Q3 - Q1  # Interquartile range
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

In [52]:
while True:
    prev_shape = df1.shape[0]
    for column in df1.select_dtypes(include=['int64', 'float64']).columns:
        df1 = remove_outliers(df1, column)
    # Stop when no more rows are dropped
    if df1.shape[0] == prev_shape:
        break

In [88]:
set(df1['AirportFrom'].unique())==set(df1['AirportTo'].unique())

True

In [54]:
df1

,id,Airline,Flight,AirportFrom,AirportTo,DayOfWeek,Time,Length,Delay
0,1,CO,269,SFO,IAH,3,15,205,1
1,2,US,1558,PHX,CLT,3,15,222,1
2,3,AA,2400,LAX,DFW,3,20,165,1
3,4,AA,2466,SFO,DFW,3,20,195,1
4,5,AS,108,ANC,SEA,3,30,202,0
...,...,...,...,...,...,...,...,...,...
539374,539375,DL,2354,LAX,ATL,5,1435,255,0
539375,539376,FL,58,LAX,ATL,5,1435,250,0
539376,539377,B6,717,JFK,SJU,5,1439,220,1
539377,539378,B6,739,JFK,PSE,5,1439,223,1
539380,539381,FL,609,SFO,MKE,5,1439,255,0

In [55]:
df1.reset_index(drop=True,inplace=True)

In [56]:
df1.dtypes

id              int64
Airline        object
Flight          int64
AirportFrom    object
AirportTo      object
DayOfWeek       int64
Time            int64
Length          int64
Delay           int64
dtype: object

In [57]:
df1.shape

(502611, 9)

In [ ]:
df=pd.get_dummies(df1,drop_first=True,columns=['Airline','AirportFrom','AirportTo'])

In [59]:
df.shape

(502611, 608)

In [60]:
from sklearn.preprocessing import MinMaxScaler

In [61]:
scaler=MinMaxScaler()

In [116]:
pd.set_option('display.max_columns', None)
df[(df['id']==5)]

,id,Flight,DayOfWeek,Time,Length,Delay,Airline_9E,Airline_AA,Airline_AS,Airline_B6,Airline_CO,Airline_DL,Airline_EV,Airline_F9,Airline_FL,Airline_HA,Airline_MQ,Airline_OH,Airline_OO,Airline_UA,Airline_US,Airline_WN,Airline_XE,Airline_YV,AirportFrom_ABE,AirportFrom_ABI,AirportFrom_ABQ,AirportFrom_ABR,AirportFrom_ABY,AirportFrom_ACT,AirportFrom_ACV,AirportFrom_ACY,AirportFrom_ADK,AirportFrom_ADQ,AirportFrom_AEX,AirportFrom_AGS,AirportFrom_ALB,AirportFrom_AMA,AirportFrom_ANC,AirportFrom_ASE,AirportFrom_ATL,AirportFrom_ATW,AirportFrom_AUS,AirportFrom_AVL,AirportFrom_AVP,AirportFrom_AZO,AirportFrom_BDL,AirportFrom_BET,AirportFrom_BFL,AirportFrom_BGM,AirportFrom_BGR,AirportFrom_BHM,AirportFrom_BIL,AirportFrom_BIS,AirportFrom_BKG,AirportFrom_BLI,AirportFrom_BMI,AirportFrom_BNA,AirportFrom_BOI,AirportFrom_BOS,AirportFrom_BQK,AirportFrom_BQN,AirportFrom_BRO,AirportFrom_BRW,AirportFrom_BTM,AirportFrom_BTR,AirportFrom_BTV,AirportFrom_BUF,AirportFrom_BUR,AirportFrom_BWI,AirportFrom_BZN,AirportFrom_CAE,AirportFrom_CAK,AirportFrom_CDC,AirportFrom_CDV,AirportFrom_CEC,AirportFrom_CHA,AirportFrom_CHO,AirportFrom_CHS,AirportFrom_CIC,AirportFrom_CID,AirportFrom_CLD,AirportFrom_CLE,AirportFrom_CLL,AirportFrom_CLT,AirportFrom_CMH,AirportFrom_CMI,AirportFrom_CMX,AirportFrom_COD,AirportFrom_COS,AirportFrom_COU,AirportFrom_CPR,AirportFrom_CRP,AirportFrom_CRW,AirportFrom_CSG,AirportFrom_CVG,AirportFrom_CWA,AirportFrom_CYS,AirportFrom_DAB,AirportFrom_DAL,AirportFrom_DAY,AirportFrom_DBQ,AirportFrom_DCA,AirportFrom_DEN,AirportFrom_DFW,AirportFrom_DHN,AirportFrom_DLH,AirportFrom_DRO,AirportFrom_DSM,AirportFrom_DTW,AirportFrom_EAU,AirportFrom_ECP,AirportFrom_EGE,AirportFrom_EKO,AirportFrom_ELM,AirportFrom_ELP,AirportFrom_ERI,AirportFrom_EUG,AirportFrom_EVV,AirportFrom_EWN,AirportFrom_EWR,AirportFrom_EYW,AirportFrom_FAI,AirportFrom_FAR,AirportFrom_FAT,AirportFrom_FAY,AirportFrom_FCA,AirportFrom_FLG,AirportFrom_FLL,AirportFrom_FLO,AirportFrom_FNT,AirportFrom_FSD,AirportFrom_FSM,AirportFrom_FWA,AirportFrom_GCC,AirportFrom_GEG,AirportFrom_GFK,AirportFrom_GGG,AirportFrom_GJT,AirportFrom_GNV,AirportFrom_GPT,AirportFrom_GRB,AirportFrom_GRK,AirportFrom_GRR,AirportFrom_GSO,AirportFrom_GSP,AirportFrom_GTF,AirportFrom_GTR,AirportFrom_GUC,AirportFrom_HDN,AirportFrom_HLN,AirportFrom_HNL,AirportFrom_HOU,AirportFrom_HPN,AirportFrom_HRL,AirportFrom_HSV,AirportFrom_HTS,AirportFrom_IAD,AirportFrom_IAH,AirportFrom_ICT,AirportFrom_IDA,AirportFrom_ILM,AirportFrom_IND,AirportFrom_IPL,AirportFrom_ISP,AirportFrom_ITH,AirportFrom_ITO,AirportFrom_IYK,AirportFrom_JAC,AirportFrom_JAN,AirportFrom_JAX,AirportFrom_JFK,AirportFrom_JNU,AirportFrom_KOA,AirportFrom_KTN,AirportFrom_LAN,AirportFrom_LAS,AirportFrom_LAX,AirportFrom_LBB,AirportFrom_LCH,AirportFrom_LEX,AirportFrom_LFT,AirportFrom_LGA,AirportFrom_LGB,AirportFrom_LIH,AirportFrom_LIT,AirportFrom_LMT,AirportFrom_LNK,AirportFrom_LRD,AirportFrom_LSE,AirportFrom_LWB,AirportFrom_LWS,AirportFrom_LYH,AirportFrom_MAF,AirportFrom_MBS,AirportFrom_MCI,AirportFrom_MCO,AirportFrom_MDT,AirportFrom_MDW,AirportFrom_MEI,AirportFrom_MEM,AirportFrom_MFE,AirportFrom_MFR,AirportFrom_MGM,AirportFrom_MHK,AirportFrom_MHT,AirportFrom_MIA,AirportFrom_MKE,AirportFrom_MKG,AirportFrom_MLB,AirportFrom_MLI,AirportFrom_MLU,AirportFrom_MMH,AirportFrom_MOB,AirportFrom_MOD,AirportFrom_MOT,AirportFrom_MQT,AirportFrom_MRY,AirportFrom_MSN,AirportFrom_MSO,AirportFrom_MSP,AirportFrom_MSY,AirportFrom_MTJ,AirportFrom_MYR,AirportFrom_OAJ,AirportFrom_OAK,AirportFrom_OGG,AirportFrom_OKC,AirportFrom_OMA,AirportFrom_OME,AirportFrom_ONT,AirportFrom_ORD,AirportFrom_ORF,AirportFrom_OTH,AirportFrom_OTZ,AirportFrom_PAH,AirportFrom_PBI,AirportFrom_PDX,AirportFrom_PHF,AirportFrom_PHL,AirportFrom_PHX,AirportFrom_PIA,AirportFrom_PIE,AirportFrom_PIH,AirportFrom_PIT,AirportFrom_PLN,AirportFrom_PNS,AirportFrom_PSC,AirportFrom_PSE,AirportFrom_PSG,AirportFrom_PSP,AirportFrom_PVD,AirportFrom_PWM,AirportFrom_RAP,AirportFrom_RDD,AirportFrom_RDM,AirportFrom_RDU,AirportFrom_RIC,AirportFrom_RKS,AirportFrom_RNO,AirportFrom_ROA,AirportFrom_ROC,AirportFrom_ROW,AirportFrom_RST,AirportFrom_RSW,AirportFrom_SAF,AirportFrom_SAN,AirportFrom_SAT,AirportFrom_SAV,AirportFrom_SBA,AirportFrom_SBN,AirportFrom_SBP,AirportFrom_SCC,AirportFrom_SCE,AirportFrom_SDF,AirportFrom_SEA,AirportFrom_SFO,AirportFrom_SGF,AirportFrom_SGU,AirportFrom_SHV,AirportFrom_SIT,AirportFrom_SJC,AirportFrom_SJT,AirportFrom_SJU,AirportFrom_SLC,AirportFrom_SMF,AirportFrom_SMX,AirportFrom_SNA,AirportFrom_SPI,AirportFrom_SPS,AirportFrom_SRQ,AirportFrom_STL,AirportFrom_STT,AirportFrom_STX,AirportFrom_SUN,AirportFrom_SWF,AirportFrom_SYR,AirportFrom_TEX,AirportFrom_TLH,AirportFrom_TOL,AirportFrom_TPA,AirportFrom_TRI,AirportFrom_TUL,AirportFrom_TUS,AirportFrom_TVC,AirportFrom_TWF,AirportFrom_TXK,AirportFrom_TYR,AirportFrom_TYS,AirportFrom_UTM,AirportFrom_VLD,AirportFrom_VPS,AirportFrom_WRG,AirportFrom_XNA,AirportFrom_YAK,AirportFrom_YUM,AirportTo_ABE,AirportTo_ABI,AirportTo_ABQ,AirportTo_ABR,AirportTo_ABY,AirportTo_ACT,AirportTo_ACV,AirportTo_ACY,AirportTo_ADK,AirportTo_ADQ,AirportTo_AEX,AirportTo_AGS,AirportTo_ALB,AirportTo_AMA,AirportTo_ANC,AirportTo_ASE,AirportTo_ATL,AirportTo_ATW,AirportTo_AUS,AirportTo_AVL,AirportTo_AVP,AirportTo_AZO,AirportTo_BDL,AirportTo_BET,AirportTo_BFL,AirportTo_BGM,AirportTo_BGR,AirportTo_BHM,AirportTo_BIL,AirportTo_BIS,AirportTo_BKG,AirportTo_BLI,AirportTo_BMI,AirportTo_BNA,AirportTo_BOI,AirportTo_BOS,AirportTo_BQK,AirportTo_BQN,AirportTo_BRO,AirportTo_BRW,AirportTo_BTM,AirportTo_BTR,AirportTo_BTV,AirportTo_BUF,AirportTo_BUR,AirportTo_BWI,AirportTo_BZN,AirportTo_CAE,AirportTo_CAK,AirportTo_CDC,AirportTo_CDV,AirportTo_CEC,AirportTo_CHA,AirportTo_CHO,AirportTo_CHS,AirportTo_CIC,AirportTo_CID,AirportTo_CLD,AirportTo_CLE,AirportTo_CLL,AirportTo_CLT,AirportTo_CMH,AirportTo_CMI,AirportTo_CMX,AirportTo_COD,AirportTo_COS,AirportTo_COU,AirportTo_CPR,AirportTo_CRP,AirportTo_CRW,AirportTo_CSG,AirportTo_CVG,AirportTo_CWA,AirportTo_CYS,AirportTo_DAB,AirportTo_DAL,AirportTo_DAY,AirportTo_DBQ,AirportTo_DCA,AirportTo_DEN,AirportTo_DFW,AirportTo_DHN,AirportTo_DLH,AirportTo_DRO,AirportTo_DSM,AirportTo_DTW,AirportTo_EAU,AirportTo_ECP,AirportTo_EGE,AirportTo_EKO,AirportTo_ELM,AirportTo_ELP,AirportTo_ERI,AirportTo_EUG,AirportTo_EVV,AirportTo_EWN,AirportTo_EWR,AirportTo_EYW,AirportTo_FAI,AirportTo_FAR,AirportTo_FAT,AirportTo_FAY,AirportTo_FCA,AirportTo_FLG,AirportTo_FLL,AirportTo_FLO,AirportTo_FNT,AirportTo_FSD,AirportTo_FSM,AirportTo_FWA,AirportTo_GCC,AirportTo_GEG,AirportTo_GFK,AirportTo_GGG,AirportTo_GJT,AirportTo_GNV,AirportTo_GPT,AirportTo_GRB,AirportTo_GRK,AirportTo_GRR,AirportTo_GSO,AirportTo_GSP,AirportTo_GTF,AirportTo_GTR,AirportTo_GUC,AirportTo_HDN,AirportTo_HLN,AirportTo_HNL,AirportTo_HOU,AirportTo_HPN,AirportTo_HRL,AirportTo_HSV,AirportTo_HTS,AirportTo_IAD,AirportTo_IAH,AirportTo_ICT,AirportTo_IDA,AirportTo_ILM,AirportTo_IND,AirportTo_IPL,AirportTo_ISP,AirportTo_ITH,AirportTo_ITO,AirportTo_IYK,AirportTo_JAC,AirportTo_JAN,AirportTo_JAX,AirportTo_JFK,AirportTo_JNU,AirportTo_KOA,AirportTo_KTN,AirportTo_LAN,AirportTo_LAS,AirportTo_LAX,AirportTo_LBB,AirportTo_LCH,AirportTo_LEX,AirportTo_LFT,AirportTo_LGA,AirportTo_LGB,AirportTo_LIH,AirportTo_LIT,AirportTo_LMT,AirportTo_LNK,AirportTo_LRD,AirportTo_LSE,AirportTo_LWB,AirportTo_LWS,AirportTo_LYH,AirportTo_MAF,AirportTo_MBS,AirportTo_MCI,AirportTo_MCO,AirportTo_MDT,AirportTo_MDW,AirportTo_MEI,AirportTo_MEM,AirportTo_MFE,AirportTo_MFR,AirportTo_MGM,AirportTo_MHK,AirportTo_MHT,AirportTo_MIA,AirportTo_MKE,AirportTo_MKG,AirportTo_MLB,AirportTo_MLI,AirportTo_MLU,AirportTo_MMH,AirportTo_MOB,AirportTo_MOD,AirportTo_MOT,AirportTo_MQT,AirportTo_MRY,AirportTo_MSN,AirportTo_MSO,AirportTo_MSP,AirportTo_MSY,AirportTo_MTJ,AirportTo_MYR,AirportTo_OAJ,AirportTo_OAK,AirportTo_OGG,AirportTo_OKC,AirportTo_OMA,AirportTo_OME,AirportTo_ONT,AirportTo_ORD,AirportTo_ORF,AirportTo_OTH,AirportTo_OTZ,AirportTo_PAH,AirportTo_PBI,AirportTo_PDX,AirportTo_PHF,AirportTo_PHL,AirportTo_PHX,AirportTo_PIA,AirportTo_PIE,AirportTo_PIH,AirportTo_PIT,AirportTo_PLN,AirportTo_PNS,AirportTo_PSC,AirportTo_PSE,AirportTo_PSG,AirportTo_PSP,AirportTo_PVD,AirportTo_PWM,AirportTo_RAP,AirportTo_RDD,AirportTo_RDM,AirportTo_RDU,AirportTo_RIC,AirportTo_RKS,AirportTo_RNO,AirportTo_ROA,AirportTo_ROC,AirportTo_ROW,AirportTo_RST,AirportTo_RSW,AirportTo_SAF,AirportTo_SAN,AirportTo_SAT,AirportTo_SAV,AirportTo_SBA,AirportTo_SBN,AirportTo_SBP,AirportTo_SCC,AirportTo_SCE,AirportTo_SDF,AirportTo_SEA,AirportTo_SFO,AirportTo_SGF,AirportTo_SGU,AirportTo_SHV,AirportTo_SIT,AirportTo_SJC,AirportTo_SJT,AirportTo_SJU,AirportTo_SLC,AirportTo_SMF,AirportTo_SMX,AirportTo_SNA,AirportTo_SPI,AirportTo_SPS,AirportTo_SRQ,AirportTo_STL,AirportTo_STT,AirportTo_STX,AirportTo_SUN,AirportTo_SWF,AirportTo_SYR,AirportTo_TEX,AirportTo_TLH,AirportTo_TOL,AirportTo_TPA,AirportTo_TRI,AirportTo_TUL,AirportTo_TUS,AirportTo_TVC,AirportTo_TWF,AirportTo_TXK,AirportTo_TYR,AirportTo_TYS,AirportTo_UTM,AirportTo_VLD,AirportTo_VPS,AirportTo_WRG,AirportTo_XNA,AirportTo_YAK,AirportTo_YUM
4,5,108,3,30,202,0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [63]:
X=df.drop(columns=['Delay','id','Flight'])
y = df['Delay']
X_scaled=scaler.fit_transform(X)

In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=200)

Classification

In [70]:
import xgboost as xgb

In [71]:
model=xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss')
model.fit(X_train,y_train)

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [10:37:38] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [72]:
y_pred=model.predict(X_test)

In [73]:
from sklearn.metrics import accuracy_score, classification_report

In [74]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.6670413736159884
Report:
               precision    recall  f1-score   support

           0       0.66      0.82      0.73     56038
           1       0.68      0.48      0.56     44485

    accuracy                           0.67    100523
   macro avg       0.67      0.65      0.65    100523
weighted avg       0.67      0.67      0.66    100523

In [75]:
print(df['Delay'].value_counts(normalize=True))

Delay
0    0.557853
1    0.442147
Name: proportion, dtype: float64

In [76]:
dict1={'model':model,'scaler':scaler, 'columns': X.columns.tolist()}

In [77]:
import pickle
with open("airlines_delay.pkl",'wb') as obj1:
  pickle.dump(dict1,obj1)

In [78]:
with open("airlines_delay.pkl",'rb') as obj2:
  var1=pickle.load(obj2)